baseurl: /
branch-prefix: branch_
email: ak@flowbrew.ru
exclude:
- checkout/
- watch
- bake_images
- README.md
- pybrew
- .cache
- node_modules
footer:
  blog: блог
  contacts: контакты
  payment: оплата
  privacypolicy: политика конфиденциальности
  refund: гарантии и возврат
  shipment: доставка
  shop: магазин чая матча
  signature: © 2019, Flow Brew
github-branch: master
github-commit-sha: b24463bb8f2f2b02d86133bc95287c491e321a25
github-repo: null
no-index: false
permalink: /blog/:title
plugins:
- jekyll-redirect-from
products:
  matcha:
    currency: RUB
    id: flowbrew60
    price: 3880
    quantity: 5
    shipping: 100
    weight: 60
sass:
  load_paths:
  - _sass
  - node_modules
  style: compressed
title: Flow Brew
traffic-allocation:
  ? ''
  : 0.5
  jupyter: 0.5
whitelist:
- jekyll-redirect-from
