baseurl: /
branch-prefix: branch_
email: ak@flowbrew.ru
exclude:
- checkout/
- watch
- bake_images
- README.md
- pybrew
- .cache
- node_modules
footer:
  blog: блог
  contacts: контакты
  payment: оплата
  privacypolicy: политика конфиденциальности
  refund: гарантии и возврат
  shipment: доставка
  shop: магазин чая матча
  signature: © 2019, Flow Brew
github-branch: master
github-commit-sha: a38893f97a107cdc5ce7e3610099ef922c2c1f05
github-repo: null
no-index: false
permalink: /blog/:title
plugins:
- jekyll-redirect-from
products:
  matcha:
    currency: RUB
    fast_shiping: 1100
    id: flowbrew60
    price: 3880
    quantity: 4
    shipping: 100
    weight: 60
sass:
  load_paths:
  - _sass
  - node_modules
  style: compressed
title: Flow Brew
traffic-allocation:
  ? ''
  : 1.0
whitelist:
- jekyll-redirect-from
