baseurl: branch_speedup_npm_deps/
email: ak@flowbrew.ru
exclude:
- checkout/
- watch
- bake_images
- README.md
- pybrew
- .cache
- node_modules
footer:
  blog: блог
  contacts: контакты
  payment: оплата
  privacypolicy: политика конфиденциальности
  refund: гарантии и возврат
  shipment: доставка
  shop: магазин чая матча
  signature: © 2019, Flow Brew
github-branch: speedup_npm_deps
github-commit-sha: 3246045073c41f7d317b36dc7edf17e526727fd0
github-repo: null
no-index: true
permalink: /blog/:title
plugins:
- jekyll-redirect-from
products:
  matcha:
    currency: RUB
    id: flowbrew60
    price: 3880
    quantity: 5
    shipping: 100
    weight: 60
sass:
  load_paths:
  - _sass
  - node_modules
  style: compressed
title: Flow Brew
whitelist:
- jekyll-redirect-from
