baseurl: branch_low_schedule_time/
branch-prefix: branch_
email: ak@flowbrew.ru
exclude: [checkout/, watch, bake_images, README.md, pybrew, .cache, node_modules]
footer: {blog: блог, contacts: контакты, payment: оплата, privacypolicy: политика
    конфиденциальности, refund: гарантии и возврат, shipment: доставка, shop: магазин
    чая матча, signature: '© 2019, Flow Brew'}
github-branch: low_schedule_time
github-commit-sha: 9024d6da886a02e46cade2628d2cca420f40140e
github-repo: null
no-index: true
permalink: /blog/:title
plugins: [jekyll-redirect-from]
products:
  matcha: {currency: RUB, id: flowbrew60, price: 3880, quantity: 5, shipping: 100,
    weight: 60}
sass:
  load_paths: [_sass, node_modules]
  style: compressed
title: Flow Brew
traffic-allocation: {}
whitelist: [jekyll-redirect-from]
