baseurl: branch_t2/
email: ak@flowbrew.ru
exclude:
- checkout/
- watch
- bake_images
- README.md
- pybrew
- .cache
footer:
  blog: блог
  contacts: контакты
  payment: оплата
  privacypolicy: политика конфиденциальности
  refund: гарантии и возврат
  shipment: доставка
  shop: магазин чая матча
  signature: © 2019, Flow Brew
github-branch: t2
github-commit-sha: e8831c14d4eb980d19c6a4239f417b63d51c2d43
github-repo: null
no-index: true
permalink: /blog/:title
plugins:
- jekyll-redirect-from
products:
  matcha:
    currency: RUB
    id: flowbrew60
    price: 3880
    quantity: 5
    shipping: 100
    weight: 60
sass:
  sass_dir: _sass
  style: compressed
title: Flow Brew
whitelist:
- jekyll-redirect-from
